# Generated by Django 6.0.7 on 2026-07-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Corporate', 'Corporate'), ('Beach Party', 'Beach Party'), ('School Event', 'School Event'), ('Festival', 'Festival'), ('Other', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('guests', models.PositiveIntegerField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
