# Generated by Django 6.0.7 on 2026-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='headsets',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
