# Generated by Django 6.0.7 on 2026-07-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_duration_booking_headsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday Party', 'Birthday Party'), ('Corporate Event', 'Corporate Event'), ('Beach Party', 'Beach Party'), ('School Event', 'School Event'), ('Church Event', 'Church Event'), ('Festival', 'Festival'), ('Private Party', 'Private Party'), ('Other', 'Other')], max_length=30),
        ),
    ]
