# Generated by Django 6.0.7 on 2026-07-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_amount_paid_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(choices=[('Headset', 'Silent Disco Headset'), ('Transmitter', 'Audio Transmitter'), ('Charging Case', 'Charging Case')], max_length=30, unique=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('maintenance_quantity', models.PositiveIntegerField(default=0, help_text='Units currently out of service and unavailable for booking.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipment Inventory',
                'verbose_name_plural': 'Equipment Inventory',
                'ordering': ['equipment_type'],
            },
        ),
    ]
