# Generated by Django 6.0.7 on 2026-07-11 05:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_quotation_invoice_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units affected.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('resolved_at', models.DateField(blank=True, help_text='Leave blank while the units are still under maintenance.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='booking.equipmentinventory')),
            ],
            options={
                'verbose_name': 'Equipment Maintenance Log',
                'verbose_name_plural': 'Equipment Maintenance Logs',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
    ]
