# Generated by Django 6.0.7 on 2026-07-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_user_cancellationrequest_customerprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('Weddings', 'Weddings'), ('Birthdays', 'Birthdays'), ('Corporate', 'Corporate'), ('Beach', 'Beach'), ('School', 'School'), ('Festival', 'Festival'), ('Setup', 'Setup')], max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Shown as the small tag overlay on the photo, and as its alt text. Defaults to the category name if left blank.', max_length=150)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Photos with the same number fall back to newest-first.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the public Gallery page without deleting it.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
    ]
