# Generated by Django 6.0.7 on 2026-07-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown as the small tag overlay on the photo, and as its alt text. Optional.', max_length=150),
        ),
    ]
