# Generated by Django 6.0.7 on 2026-07-16 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_remove_galleryimage_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['display_order', '-uploaded_at'], 'verbose_name': 'Gallery Item', 'verbose_name_plural': 'Gallery Items'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Photo'), ('video', 'Video')], default='image', help_text='Whether this entry is a photo or a video clip.', max_length=5),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video',
            field=models.FileField(blank=True, help_text='Required for Video entries (mp4/webm/mov). Ignored for Photo entries. Keep clips short (under ~30s) and compressed - large files slow down the public Gallery page for visitors.', null=True, upload_to='gallery/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v'])]),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='video_poster',
            field=models.ImageField(blank=True, help_text="Optional cover image shown before a video plays. If left blank, the browser shows the video's first frame instead.", null=True, upload_to='gallery/video_posters/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Shown as the small tag overlay on the photo/video, and as its alt text. Optional.', max_length=150),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Entries with the same number fall back to newest-first.'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Required for Photo entries. Ignored for Video entries.', null=True, upload_to='gallery/'),
        ),
    ]
