"""
Django settings for decisivesounds project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load variables from a .env file in the project root (EMAIL_HOST_USER,
# EMAIL_HOST_PASSWORD, etc.) into the environment. See .env.example.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to the original dev key locally; set a real SECRET_KEY env var
# on your host (Render, etc.) in production.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-$9ydcdiu)9&++g8ky$6a+n9*rs__wqil!=gudi*3%&g08egc^1',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to True locally; set DEBUG=False as an env var in production.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Comma-separated list of allowed hostnames, e.g. "myapp.onrender.com,mysite.com".
# Render also injects RENDER_EXTERNAL_HOSTNAME automatically for the default
# *.onrender.com domain, so that's added in even if ALLOWED_HOSTS isn't set.
ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS if h not in ('localhost', '127.0.0.1')]


# Application definition

INSTALLED_APPS = [
    'booking',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'decisivesounds.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'decisivesounds.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'decisivesounds'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Optional: if DATABASE_URL is set (common with managed Postgres hosts like
# Railway, Render, Heroku, Supabase, ElephantSQL), it overrides the
# individual DB_* settings above. Requires `pip install dj-database-url`.
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.parse(_database_url, conn_max_age=600)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
    ]

# Where `collectstatic` gathers files for WhiteNoise to serve in production
# (see build.sh). Not used in local dev since STATICFILES_DIRS covers that.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Admin-uploaded content (Gallery photos & videos, Booking documents, etc. -
# anything using an ImageField/FileField). Separate from STATIC_* above,
# which is for the site's own bundled CSS/JS/images, not user uploads.
#
# Local disk storage doesn't survive in most hosting setups (e.g. Render's
# web services wipe their filesystem on every restart/redeploy), so
# uploads go to Cloudinary instead whenever CLOUDINARY_URL is set - see
# .env.example for where to get that value. Falls back to local disk if
# it isn't set, which is what local development uses.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

USE_CLOUDINARY = bool(os.environ.get('CLOUDINARY_URL'))

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if USE_CLOUDINARY
            else 'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Email — used to notify the business of new bookings (booking/views.py).
# Defaults to printing emails to the console so nothing breaks out of the
# box in development. Set real SMTP credentials via environment variables
# in production (e.g. in your host's dashboard or a .env file) — never
# commit real credentials to this file.
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'bookings@decisivesoundng.com')

# How long send_mail() will wait before treating the SMTP server as
# unreachable (booking/views.py catches this so a slow/dead mail server
# never delays the redirect to WhatsApp).
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))

# Paystack (booking/paystack.py) — secret key used server-side to
# initialize/verify transactions and check webhook signatures. Never
# commit a real key here; set it via the environment / .env file.
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '')